[package]
name = "sol-fn"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.4", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6.6", features = ["cors", "trace"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.0", features = ["v4"] }

# Solana dependencies
solana-sdk = "2.3.1"
solana-client = "2.3.1"
spl-token = "8.0.0"
spl-associated-token-account = "7.0.0"
bs58 = "0.5"
bincode = "1.3"